// react-crud-restapi/src/component/EditProductComponent.jsx
import React, { Component } from "react";
import ProductService from "../service/ProductService";

class EditProductComponent extends Component {

    constructor(props) {
        super(props);
        this.state = {
            id: '',
            name: '',
            category: '',
            price: '',
            message: null
        }
        this.getProduct = this.getProduct.bind(this);
        this.updateProduct = this.updateProduct.bind(this);
    }

    componentDidMount() {
        this.getProduct();
    }

    getProduct() {
        ProductService.getProductById(window.localStorage.getItem("productId"))
        .then( (response) => {
            let product = response.data.result;
            this.setState({
                id: product.id,
                name: product.name,
                category: product.category,
                price: product.price
            })
        });
    }

    onChange = (e) =>
        this.setState({ [e.target.name]: e.target.value });

    updateProduct = (e) => {
        e.preventDefault();
        let product = {id: this.state.id, name: this.state.name, category: this.state.category, price: this.state.price};
    
        ProductService.updateProduct(product)
        .then(res => {
            this.setState({message : 'Product updated successfully.'});
            this.props.history.push('/products');
        });
    }

    render() {
        return (
            <div>
                <h2 className="text-center">Edit Product</h2>

                <form>
                <div className="form-group">
                    <label>Name:</label>
                    <input type="text" name="name" placeholder="name" className="form-control" value={this.state.name} 
                    onChange={this.onChange} />
                </div>

                <div className="form-group">
                    <label>Category:</label>
                    <input type="text" name="category" placeholder="category" className="form-control" value={this.state.category} 
                    onChange={this.onChange} />
                </div>

                <div className="form-group">
                    <label>Price:</label>
                    <input type="text" name="price" placeholder="price" className="form-control" value={this.state.price} 
                    onChange={this.onChange} />
                </div>

                <button className="btn btn-success" onClick={this.updateProduct}>Update</button>
                </form>
            </div>
        );
    }

}

export default EditProductComponent;

// ang-crud-restapi/src/app/component/edit-product/edit-product.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from "@angular/forms";

import { Product } from '../../model/product.model';
import { Router } from '@angular/router';
import { ProductService } from '../../service/product.service';

@Component({
  selector: 'app-edit-product',
  templateUrl: './edit-product.component.html',
  styleUrls: ['./edit-product.component.css']
})
export class EditProductComponent implements OnInit {

  product: Product;
  productEditFormGroup: FormGroup;

  constructor(
    private formBuilder: FormBuilder, 
    private router: Router,
    private productService: ProductService) { }

  ngOnInit(): void {
    let productId = window.localStorage.getItem("productId");
    this.productEditFormGroup = this.formBuilder.group({
      id: ['', Validators.required],
      name: ['', Validators.required],
      category: ['', Validators.required],
      price: ['', Validators.required]
    });

    this.productService.getProductById(+productId).subscribe(
      (response) =>{
        this.productEditFormGroup.setValue(response.result);
      }
    );
  }

  onEditProduct(): void {
    this.productService.updateProduct(this.productEditFormGroup.value)
    .subscribe(
      (response) => {
        if(response.status === 200){
          alert(response.message);
          this.router.navigate(['show-product'])
        } else {
          alert(response.message);
        }
      },
      (error) => {
        alert(error);
      }
    );
  }

}

<div class="col-md-6 user-container">
    <h2 class="text-center">Edit Product</h2>
    <form [formGroup]="productEditFormGroup" (ngSubmit)="onEditProduct()">
      <div class="form-group">
        <label for="name">Name:</label>
        <input type="text" formControlName="name" placeholder="name" name="name" class="form-control" id="name">
      </div>
      <div class="form-group">
        <label for="category">Category:</label>
        <input type="text" formControlName="category" placeholder="category" name="category" class="form-control" id="category">
      </div>
      <div class="form-group">
        <label for="price">Price:</label>
        <input type="text" formControlName="price" placeholder="price" name="price" class="form-control" id="price">
      </div>
      <button class="btn btn-success">Update</button>
</form>
</div>
