// ang-crud-restapi/src/app/component/add-product/add-product.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from "@angular/forms";
import { Router } from '@angular/router';
import { ProductService } from '../../service/product.service';

@Component({
  selector: 'app-add-product',
  templateUrl: './add-product.component.html',
  styleUrls: ['./add-product.component.css']
})
export class AddProductComponent implements OnInit {

  productFormAddGroup: FormGroup;

  constructor(
    private formBuilder: FormBuilder,
    private router: Router,
    private productService: ProductService
  ) { }

  ngOnInit(): void {
  this.productFormAddGroup = this.formBuilder.group({
    id: ['', Validators.required],
    name: ['', Validators.required],
    category: ['', Validators.required],
    price: ['', Validators.required]
  });
  }

  onAddProduct(): void {
    this.productService.addProduct(this.productFormAddGroup.value).subscribe(
      (response) => {
        this.router.navigate(['show-product']);
      }
    );
  }
}

<div class="col-md-6 user-container">
    <h2 class="text-center">Add Product</h2>
    <form [formGroup]="productFormAddGroup" (ngSubmit)="onAddProduct()">
      <div class="form-group">
        <label for="name">Name:</label>
        <input type="text" formControlName="name" placeholder="name" name="name" class="form-control" id="name">
      </div>
      <div class="form-group">
        <label for="category">Category:</label>
        <input type="text" formControlName="category" placeholder="category" name="category" class="form-control" id="category">
      </div>
      <div class="form-group">
        <label for="price">Price:</label>
        <input type="text" formControlName="price" placeholder="price" name="price" class="form-control" id="price">
      </div>
      <button class="btn btn-success">Add</button>
</form>
</div>

// react-crud-restapi/src/component/AddProductComponent.jsx
import React, { Component } from "react";
import ProductService from "../service/ProductService";


class AddProductComponent extends Component {

    constructor(props) {
        super(props);
        this.state = {
            name: '',
            category: '',
            price: '',
            message: null
        }

        this.addProduct = this.addProduct.bind(this);
    }

    addProduct = (e) => {
        e.preventDefault();

        let product = {name: this.state.name, category: this.state.category, price: this.state.price};

        ProductService.addProduct(product)
        .then(res => {
            this.setState({message : 'Product added successfully.'});
            this.props.history.push('/products');
        });
    }

    onChange = (e) =>
        this.setState({ [e.target.name]: e.target.value });

    render() {
        return (
            <div>
                <h2 className="text-center">Add Product</h2>
                <form>
                <div className="form-group">
                    <label>Name:</label>
                    <input type="text" name="name" placeholder="name" className="form-control" value={this.state.name} 
                    onChange={this.onChange} />
                </div>

                <div className="form-group">
                    <label>Category:</label>
                    <input type="text" name="category" placeholder="category" className="form-control" value={this.state.category} 
                    onChange={this.onChange} />
                </div>

                <div className="form-group">
                    <label>Price:</label>
                    <input type="text" name="price" placeholder="price" className="form-control" value={this.state.price} 
                    onChange={this.onChange} />
                </div>

                <button className="btn btn-success" onClick={this.addProduct}>Add</button>
                </form>
            </div>
        );
        }
}

export default AddProductComponent;
