// ang-crud-restapi/src/app/component/show-product/show-product.component.ts
import { Component, OnInit } from '@angular/core';
import { Product } from '../../model/product.model';
import { ProductService } from '../../service/product.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-show-product',
  templateUrl: './show-product.component.html',
  styleUrls: ['./show-product.component.css']
})
export class ShowProductComponent implements OnInit {

  products: Product[];
  
  constructor(private productService: ProductService, private router: Router) { }

  ngOnInit(): void {
    this.productService.getAllProducts().subscribe( (response) =>{
      this.products = response.result;
  });
  }

  addProduct(): void {
    this.router.navigate(['add-product']);
  }

  editProduct(product: Product): void {
    window.localStorage.removeItem("productId");
    window.localStorage.setItem("productId", product.id);    
    this.router.navigate(['edit-product']);
  }

  deleteProduct(product: Product): void {
    this.productService.deleteProduct(product.id).subscribe(
      (response) => {
        this.products = this.products.filter(e => e !== product);
      });
  }
}

<div class="col-md-6 user-container">
  <h2 style="margin: auto"> Product Details</h2>
  <button class="btn btn-danger" style="width:100px" (click)="addProduct()">Add Product</button>

  <table class="table table-striped">
      <thead>
      <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Category</th>
        <th>Price</th>
      </tr>
      </thead>
      <tbody>
      <tr *ngFor="let product of products">
        <td>{{product.id}}</td>
        <td>{{product.name}}</td>
        <td>{{product.category}}</td>
        <td>{{product.price}}</td>
        <td><button class="btn btn-success" (click)="deleteProduct(product)"> Delete</button>
          <button class="btn btn-success" (click)="editProduct(product)" style="margin-left: 20px;"> Edit</button>
        </td>
      </tr>
      </tbody>

</table>
</div>

// react-crud-restapi/src/component/ShowProductComponent.jsx
import React, { Component } from 'react';
import ProductService from '../service/ProductService';

class ShowProductComponent extends Component {

    constructor(props) {
        super(props);

        this.state = {
            products: [],
            message: null
        }
        this.getAllProducts = this.getAllProducts.bind(this);
        this.addProduct = this.addProduct.bind(this);
        this.editProduct = this.editProduct.bind(this);
        this.deleteProduct = this.deleteProduct.bind(this);
    }

    componentDidMount(){
        this.getAllProducts();
    }

    getAllProducts() {
        ProductService.getAllProducts()
        .then((response) => {
            this.setState({
                products: response.data.result,
                message: response.data.message
            })
        });
    }

    deleteProduct(productId) {
        ProductService.deleteUser(productId)
           .then(response => {
               this.setState({message: 'Product deleted successfully.'});
               this.setState({products: this.state.products.filter(product => product.id !== productId)});
           })
    }

    editProduct(productId) {
        window.localStorage.setItem("productId", productId);
        this.props.history.push('/edit-product');
    }

    addProduct() {
        window.localStorage.removeItem("productId");
        this.props.history.push('/add-product');
    }

    render(){
        return(
            <div>
                <h2 className="text-center">Product Details</h2>
                <button className="btn btn-danger" style={{width:'100px'}} onClick={() => this.addProduct()}> Add Product</button>
                <table border="1" className="table table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>NAME</th>
                            <th>CATEGORY</th>
                            <th>PRICE</th>
                            <th>ACTIONS</th>
                        </tr>
                    </thead>
                    <tbody>
                        {
                            this.state.products.map(
                        product =>
                                    <tr key={product.id}>
                                        <td>{product.id}</td>
                                        <td>{product.name}</td>
                                        <td>{product.category}</td>
                                        <td>{product.price}</td>
                                        <td>
                                            <button className="btn btn-success" onClick={() => this.deleteProduct(product.id)}> Delete</button>
                                            <button className="btn btn-success" onClick={() => this.editProduct(product.id)} style={{marginLeft: '20px'}}> Edit</button>
                                        </td>
                                    </tr>
                            )
                        }
                    </tbody>
                </table>
            </div>
        );
    }
}

export default ShowProductComponent;
